server:
  port: ${sp.payable}
spring:
  application:
    name: ${sn.payable}
#  cloud:
#    sentinel:
#      transport:
#        # 控制台地址
#        dashboard: ${sentinel.dashboard}
#        port: 8720
#      eager: true
#
## 开启sentinel声明式服务熔断
#feign:
#  sentinel:
#    enabled: true

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id

