# 应用名称
server:
  port: ${sp.seata}
spring:
  application:
    name: ${sn.seata}

seata:
  tx-service-group: tx-business
  enabled: true
  service:
    # seata 服务器地址
    grouplist:
      default: ${seata.default}
    # 分配虚拟组映射，key名称与tx-service-group的值一致
    vgroup-mapping:
      tx-business: default
    # 启用全局事务
    disable-global-transaction: false